name: sl
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - pandas=0.23.4
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - pytorch=0.4.0
  - h5py=2.8
  - seaborn=0.9.0
  - pip:
    - wfdb==2.1.1
    - sacred==0.7.3
    - pymongo==3.6.1
    - mne==0.16.1
    - tensorflow==1.8
    - git+https://github.com/wookayin/tensorflow-plot.git@master
